version: 2

sources:
  - name: fec
    database: raw
    schema: fec

    tables:
      - name: cm
        columns:
          - name: cmte_id
            tests:
              - unique
      - name: cn
        columns:
          - name: cand_id
            tests:
              - unique
      - name: oppexp
        columns:
          - name: sub_id
            tests:
              - unique
      - name: itcont
        columns:
          - name: sub_id
            tests:
              - unique
      - name: dates
        columns:
          - name: datekey
            tests:
              - unique
      - name: reporttypes
        columns:
          - name: reporttypecode
            tests:
              - unique
      - name: expensecategories
        columns:
          - name: expensecategorycode
            tests:
              - unique
      - name: zipcodes
        columns:
          - name: zipcode
            tests:
              - unique
# sources: 
#   - name: northwind
#     database: raw
#     schema: northwind
#     tables:
#       - name: cm
#         columns:
#           - name: cmte_id
#             tests:
#               - unique
#       - name: Products
#         columns:
#           - name: ProductId
#             tests:
#               - unique        
#       - name: Suppliers
#         columns:
#           - name: SupplierId
#             tests:
#               - unique        
#       - name: Categories
#         columns:
#           - name: CategoryId
#             tests:
#               - unique
#       - name: Employees
#         columns:
#           - name: EmployeeId
#             tests:
#               - unique
#       - name: Shippers
#         columns:
#           - name: ShipperID
#             tests:
#               - unique      
#       - name: Orders
#         columns:
#           - name: OrderId
#             tests:
#               - unique                                                  
#       - name: Order_Details
#         tests:
#         - dbt_utils.unique_combination_of_columns:
#             combination_of_columns:
#               - OrderId
#               - ProductId
